extends SceneTree

## Writes a presentation manifest for each placeholder-backed species.
##
##   godot --headless --path . --script tools/presentation/build_placeholder_manifests.gd
##
## It runs on one machine only: the models it reads are quarantined
## (decision 0027) and nothing else has them. What it *writes* is committed, so
## a fresh clone carries manifests naming scenes it has not got — which the game
## handles by falling back, and the build accepts by knowing the path is
## quarantined.
##
## The mapping below is arbitrary and provisional. Nothing about a placeholder
## says which fakemon it stands in for, and that is a naming decision nobody has
## made.

const STANDS_IN: Dictionary[String, String] = {
	"placeholder_base": "pm0001_00",
	"placeholder_evolved": "pm0004_00",
	"placeholder_genderless": "pm0025_00",
}

const PLACEHOLDERS: String = "res://game/assets/placeholders"
const OUT: String = "res://content/presentation"


func _init() -> void:
	DirAccess.make_dir_recursive_absolute(OUT)

	var written: int = 0
	for species_id: String in STANDS_IN:
		if _write(species_id, STANDS_IN[species_id]):
			written += 1

	print("presentation: %d of %d manifests written" % [written, STANDS_IN.size()])
	if written < STANDS_IN.size():
		print("(the rest need their models installed — see tools/ in the asset pipeline)")
	quit()


func _write(species_id: String, model: String) -> bool:
	var scene_path: String = "%s/%s/%s.tscn" % [PLACEHOLDERS, model, model]
	if not ResourceLoader.exists(scene_path):
		return false

	var mapping: ClipMap.Mapping = _clips_of(scene_path)
	if mapping == null:
		return false

	var lines: PackedStringArray = PackedStringArray()
	lines.append("# Generated by tools/presentation/build_placeholder_manifests.gd")
	lines.append("# The model is a placeholder and lives on one machine only.")
	lines.append("")
	lines.append("scene: %s" % scene_path)
	lines.append("height: 1.0")
	lines.append("")
	lines.append("clips:")

	for slot: String in mapping.slots():
		lines.append("  %s:" % slot)
		for take: String in mapping.takes[slot]:
			lines.append("    - %s" % take)

	_list(lines, "extras", mapping.extras)
	_list(lines, "stow", mapping.stow)

	var file: FileAccess = FileAccess.open("%s/%s.yaml" % [OUT, species_id], FileAccess.WRITE)
	if file == null:
		return false
	file.store_string("\n".join(lines) + "\n")
	file.close()
	return true


## Every clip the model carries, mapped. Nothing is dropped — a name that
## matches no slot becomes an extra, which is what makes the manifest's count
## checkable against the model's.
func _clips_of(scene_path: String) -> ClipMap.Mapping:
	var packed: PackedScene = load(scene_path)
	if packed == null:
		return null

	var root: Node = packed.instantiate()
	var player: AnimationPlayer = _player_under(root)
	var mapping: ClipMap.Mapping = null
	if player != null:
		mapping = ClipMap.of(player.get_animation_list())
	root.free()
	return mapping


func _player_under(node: Node) -> AnimationPlayer:
	for child: Node in node.get_children():
		if child is AnimationPlayer:
			return child as AnimationPlayer
		var deeper: AnimationPlayer = _player_under(child)
		if deeper != null:
			return deeper
	return null


func _list(lines: PackedStringArray, key: String, names: PackedStringArray) -> void:
	if names.is_empty():
		return
	lines.append("")
	lines.append("%s:" % key)
	for name: String in names:
		lines.append("  - %s" % name)
